name: Snyk Code Scan
on:
  push:
    branches: [custom-config]
  pull_request:
    branches: [custom-config]
jobs:
  snyk-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Snyk
        uses: snyk/actions/setup@master
      - name: Snyk Code Test
        run: snyk code test --severity-threshold=high --org=my-org
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
